verdict:
  anchors:
    blur:
      good: -0.0597
      bad: 1.3883
    shadow:
      good: 0.1188
      bad: 1.5875
    skew:
      good: 0.193
      bad: 0.836
    cropped:
      good: -0.6854
      bad: 1.7743
    low_resolution:
      good: -0.1176
      bad: 1.6471
    noise:
      good: -0.1161
      bad: 0.3836
    streaks:
      good: 0.0138
      bad: 1.5931
    unreadable:
      good: 0.4506
      bad: 0.6313
